apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
type: Opaque
data:
  rabbitmq-user: dXNlci1yYWJiaXQ=
  rabbitmq-password: cmFuZG9tLXBhc3N3b3JkLXJhYmJpdA==
  rabbitmq-erlang-cookie: cmFuZG9tLWNvb2tpZS1yYWJiaXQ=
