apiVersion: v1
data:
  init.sh: |
    if [ "$HOSTNAME" == "mongod-0" ]; then
      mongo --eval 'rs.initiate({_id: "rs0", version: 1, members: [ { _id: 0, host : "mongod-0.mongodb-service.default.svc.cluster.local:27017" }, { _id: 1, host : "mongod-1.mongodb-service.default.svc.cluster.local:27017" }, { _id: 2, host : "mongod-2.mongodb-service.default.svc.cluster.local:27017" } ]});';
      sleep 20;
      mongo --eval "db = db.getSiblingDB('admin'); db.createUser({ user: \"$MONGO_USER\", pwd: \"$MONGO_PASSWORD\", roles: [{ role: 'userAdminAnyDatabase', db: 'admin' }]});";
      mongo -u $MONGO_USER -p $MONGO_PASSWORD --authenticationDatabase admin --eval "db = db.getSiblingDB(\"$MONGO_DATABASE\"); db.createUser({ user: \"$MONGO_USER\", pwd: \"$MONGO_PASSWORD\", roles: [{ role: 'dbOwner', db: \"$MONGO_DATABASE\" }]});";
    fi;
kind: ConfigMap
metadata:
  name: mongo-init-script
