apiVersion: v1
kind: PersistentVolume
metadata:
    name: glusterfs
spec:
    capacity:
        storage: 10Gi
    accessModes:
    - ReadWriteMany
    glusterfs:
        endpoints: glusterfs
        path: /gv1
    storageClassName: gluster-storage
    persistentVolumeReclaimPolicy: Retain
